### ISSUE TITLE
Gpio or voice activation?

### ISSUE THREAD

**Issue by marksev1** [ewenchou/alexa-client#1]
Cool project and blog. Are you maybe planning to add also activation with a button or hotword activation (always listening for hotword) and then after that activate speech from a usb microphone so that alexa could respond.

**Comment by ewenchou** [comment]
Thanks! There is a great repo that includes a hardware button [here](https://github.com/sammachin/AlexaPi). I referenced it in one of my blog posts but you may have missed it :)

No plans to do a hotword right now. 

Also, Amazon recently released a very detailed demo + guide on how to turn a Pi into AVS device. You can find it [here](https://github.com/amzn/alexa-avs-raspberry-pi)

**Comment by marksev1** [comment]
Thats sammachins I have some security considerations since you have to deploy a heroku app nonlocally with all the credentials that one i dont want to use. The amazon one doesnt have a button supported yet.

**Comment by marksev1** [comment]
Yours looks the best, do you have some pro-tip how I could implement that for myself? (The button support)
