### ISSUE TITLE
AVS response time

### ISSUE THREAD

**Issue by dly9014** [ewenchou/alexa-client#2]
Hi, I came across your great work in hopes of finding someone who might be able to improve the response time from AVS with an RPI. Check out: [https://forums.developer.amazon.com/questions/30086/streaming-audio-to-avs-to-improve-unacceptable-res.html](url), amazon replied with help on how to do this, but it will probably take me weeks to figure it out. I was wondering if you might consider modifying your alexa_client.py project code in the ask function to enable chunked streaming vs file input. It would help with the 3-5 second response time. Mine is actually more like 5-10 seconds :(. I would love to see how it is done and will share if I figure it out, but my python skills are at a beginner level.  Thanks for your project!

**Comment by ewenchou** [comment]
Sorry for taking so long to get to this issue. I tried opening the link you pasted but it didn't work. Just went to the frontpage of the developer forums. Maybe this issue is already resolved by itself? I have not had any problem on my RPi. Thanks.
