### ISSUE TITLE
small new fixes

### ISSUE THREAD

**Issue by ibaranov-cp** [ewenchou/alexa-client#4]
- cherrypy is now a requirement, should be added to requirments.txt
- Rename Product ID as Device Type ID to more closely match Amazon description (minor confusion)
  Seems to work now! :)

**Comment by ewenchou** [comment]
Thanks for the suggestions. I've updated it. Kept `cherrypy` in `auth_web_requirements.txt` since it isn't actually required by `alexa_client` itself.
