### ISSUE TITLE
Blank mp3 file while running tests

### ISSUE THREAD

**Issue by weedgrease** [ewenchou/alexa-client#5]
Hey there. First off thanks for your hard work on the package!

I've ran the tests on Windows 10 with python 2.7 and, after getting a refresh token, saving it, etc. I get a blank mp3 file in my tmp directory. I get a 204 response code from `ask()` but not sure how Amazon provides responses.

Any ideas?

**Comment by ewenchou** [comment]
I haven't tried using the code on Windows, but if I remember correctly the empty HTTP 204 response means that Alexa Voice Service was not able to interpret the request (i.e. the WAV file that got sent).

Are you using the test scripts or you're calling the `ask()` method with some other input? 

The test scripts come with sample WAV files. I just tried on my Ubuntu system again and those work.

**Comment by JannKleen** [comment]
I just had a similar error when using wrong sampling rate / resolution and number of channels.
You should be using 16 bit; 16000 Hz; mono wav files.

**Comment by raju249** [comment]
Then how do we solve this problem @JannKleen

**Comment by raju249** [comment]
Okay,
So I think I solved this issue. I had it worked on my windows machine.
We need to read raw audio data and also remove those file path and pass on the audio file name from the same folder.
