### ISSUE TITLE
python test_ask.py NG

### ISSUE THREAD

**Issue by leemack** [ewenchou/alexa-client#8]
Dear Sir:
I followed your description step by step,

I almost finish them but stop at "python test_ask.py"

There seemed something wrong, especially the refersh token which i got from a new web browser like follow:
Atzr|IwEBIKjPbC5A8gTn4NpC0ddzNyANkHJdxdSm7qOaSHnUXHedSgqixcaYgzB_m6ZO6LKN1z8XHaDJOD_DsoYdlLVpQi5KDjLMWQ1RmqGEaaByfyXNOLTLKwn79rp5W4YDBdsbZpoiKI1NDBFuHgPZSTnECx5YBvF1WvFe_OnIS66cxIv8g5jSXg8fRp2FFQ9asHBNosj8UlJi08Z-13jOnY-pYcSqie2r-gXuDkQV5hHNnOXdQasOGOytLjl9T_T7XTzp1pdMU-h1X7dW9EvZY5TKjjo3FJ_X-gK9rZz0y9B3cgDBnlJvBtWi5AAI0FsSGNXrw1ho4L7Ln0OfBFLC2fHbrurg2SSmJw-MkRfkqDq5VQewy-wMdHTZSzfl3Dar_VeOswpPOlFaNfY2eS_hQkR4GJvsy5WCBVO0pRtVIr42X2dF2dRV3_ejDphG11bkrYEP1JmEmC7fCscI58-H0lIXY7JgyDRjvmnZ19GyCVyYT1oxc63-LcLx99hjt4_HdCYCcE89RtfRPuQ-l5ZfHKoIsa3ZWiPZ3qJ1RJDsT7iQ1Y0K4w

Can You help me? or which video I can see in youtube?

Thanks in advanced.

leemack

**Comment by ewenchou** [comment]
The official guide page is probably the best to follow if you're having trouble with the authorization.
https://developer.amazon.com/docs/alexa-voice-service/authorize-companion-site.html
